### ISSUE TITLE
Difference in commands for running OMP and IMP Pruning

### ISSUE THREAD

**Issue by veds12** [OPTML-Group/Unlearn-Sparse#2]
There seems to be no difference in the commands for using OMP and IMP pruning as mentioned in the README (except for the fact that the OMP command takes `rate` as an argument and the IMP command takes `pruning_times` as an argument:

## OMP 

`python -u main_imp.py --data ./data --dataset $data --arch $arch --prune_type rewind_lt --rewind_epoch 8 --save_dir ${save_dir} --rate ${rate} --pruning_times 2 --num_workers 8`

## IMP

`python -u main_imp.py --data ./data --dataset $data --arch $arch --prune_type rewind_lt --rewind_epoch 8 --save_dir ${save_dir} --rate 0.2 --pruning_times ${pruning_times} --num_workers 8`

 Is this a mistake? Which method would the command mentioned run by default? I am not able to determine that by looking at the code. I would like to run OMP pruning, what would be the correct command to do so?

**Comment by ljcc0930** [comment]
Hi, OMP is one-shot pruning with the rewinding, *i.e.* it only takes the pruning process once, while IMP is the iterative one with multiple pruning times. So basically, they share the same code base. You can get the OMP process by setting the `--pruning_times` to 2, as the former command indicated (Sorry for the confusion, I thought the `pruning_times` here meant the times of the training process, we would fix it later).

Please feel free to ask if you have further questions!
