### ISSUE TITLE
Mistake in code?

### ISSUE THREAD

**Issue by rohan1561** [OPTML-Group/Unlearn-Sparse#6]
Hello, is there a problem in the line 259 of dataset.py? It appears as if indexes_to_replace has been considered to be an int and is supposed to be a list.. was the or clause supposed to be added to line 256 with num_indexes_to_replace? Thanks!

**Comment by jinghanjia** [comment]
Thank you for highlighting this issue. We have corrected the mistake, which occurred during the code cleanup process. Your assistance is greatly appreciated.
