### ISSUE TITLE
Question about the standard deviation over 10 independent trials

### ISSUE THREAD

**Issue by meng-ding** [OPTML-Group/Unlearn-Sparse#9]
Hi, I am glad to read your excellent work.

I have a question regarding the experiment for calculating the standard deviation over 10 independent trials.

Could you please clarify whether these trials were conducted across various replacement classes or if they were performed with different seeds within a single replacement class?

Thank you for your time and assistance.

**Comment by ljcc0930** [comment]
Hi @meng-ding, thanks for your question. The results of class-wise unlearning in the paper are within one class with different seeds. Similar observations exist for other classes as well.
